apiVersion: v1                                                                                             
kind: Service
metadata:
  name: hbayraktar-deamon
spec:
  type: NodePort
  selector:
    app: hbayraktar-deamon
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
    targetPort: 8080

